# Generated by Django 3.2.25 on 2024-10-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_table',
            name='idproof',
        ),
        migrations.RemoveField(
            model_name='student_table',
            name='post',
        ),
    ]
