# Generated by Django 3.2.25 on 2024-10-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_feedback_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('report', models.BigIntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
