# Generated by Django 3.2.25 on 2024-10-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_report_table_counsilor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_table',
            old_name='date',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='feedback_table',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback_table',
            name='Feedback',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
