# Generated by Django 3.2.25 on 2024-10-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20241019_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_table',
            old_name='Date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='feedback_table',
            name='Feedback',
        ),
        migrations.AddField(
            model_name='feedback_table',
            name='feedback',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report_table',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student_table'),
            preserve_default=False,
        ),
    ]
