# Generated by Django 3.2.25 on 2024-10-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20241019_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_table',
            name='reply',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
