# Generated by Django 3.2.25 on 2024-10-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_report_table_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_table',
            name='REGISTER',
        ),
    ]
