# Generated by Django 3.2.25 on 2024-10-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_teacher_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_table',
            name='type',
        ),
        migrations.RemoveField(
            model_name='teacher_table',
            name='type',
        ),
        migrations.AddField(
            model_name='counsilor_table',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
